vich_uploader:
  db_driver: orm

  mappings:
    images:
      uri_prefix: /images/products
      upload_destination: "%kernel.project_dir%/public/images"
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    file_upload:
      uri_prefix: /uploads
      upload_destination: "%kernel.project_dir%/public/uploads"

  metadata:
        type: annotation

    mappings:
        products:
            uri_prefix: /uploads/images/products
            upload_destination: '%kernel.project_dir%/public/uploads/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
